version: "3.8"

services:
  php-fpm:
    container_name: php-fpm
    build:
      # Указываем где находится проект, к которому применяется сборка
      context: ./../../
      dockerfile: ./deployment/docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - /var/www/vendor/
      - ./../../:/var/www/

  nginx-store:
    container_name: nginx-store
    build:
      context: .//nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ../../:/var/www:rw
    depends_on:
      - php-fpm
